/*
 * Copyright 2022-Present Okta, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.okta.authfoundation.credential.kmp.storage

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor

/**
 * Cross-platform Room database for persisting OAuth2 tokens.
 *
 * Platform-specific database builders create instances via [TokenDatabaseConstructor].
 */
@Database(
    entities = [TokenEntity::class, SettingEntity::class],
    version = TokenDatabase.VERSION
)
@ConstructedBy(TokenDatabaseConstructor::class)
abstract class TokenDatabase : RoomDatabase() {
    internal abstract fun tokenDao(): TokenDao

    internal abstract fun settingDao(): SettingDao

    companion object {
        internal const val VERSION = 1
        internal const val DB_NAME = "common_token_database"
    }
}

/**
 * Room KMP constructor for [TokenDatabase].
 *
 * The `actual` implementations are generated by Room's KSP processor for each platform target.
 */
@Suppress("KotlinNoActualForExpect")
expect object TokenDatabaseConstructor : RoomDatabaseConstructor<TokenDatabase>
