package com.okta.directauth.app.screen

import android.util.Log
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material3.Button
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalFocusManager
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.tooling.preview.PreviewLightDark
import androidx.compose.ui.unit.dp
import com.okta.directauth.app.ui.theme.DirectAuthAppTheme
import com.okta.directauth.app.util.BLANK_FIELD_ERROR
import com.okta.directauth.app.util.rememberCancellableJob
import com.okta.directauth.app.util.validateNotBlank
import kotlinx.coroutines.Job

private const val TAG = "CodeEntryScreen"

/**
 * Code entry screen for entering verification codes (OTP, SMS, Voice).
 *
 * This screen is displayed when the user needs to enter a numeric verification code
 * sent via SMS, Voice call, or generated by an authenticator app (OTP).
 *
 * The screen displays:
 * - An "Enter a code" title
 * - Username display
 * - A numeric text field for code entry
 * - A "Next" button to submit the code
 * - A "Verify with something else" link (optional) to choose a different auth method
 * - A "Back to sign in" link to return to username entry
 *
 * Features:
 * - Numeric keyboard for easier code entry
 * - Validates that the code field is not blank before submitting
 * - Disables UI during code verification to prevent multiple submissions
 * - Automatically cancels ongoing verification if user navigates away
 * - Reusable across different code-based authentication methods (OTP, SMS, Voice)
 *
 * @param username The username being authenticated. Displayed on screen.
 * @param backToSignIn Callback to return to the username entry screen.
 * @param verifyWithSomethingElse Optional callback to select a different authentication method.
 *                                 If null, the "Verify with something else" link is not shown.
 * @param next Callback invoked when user submits a valid code.
 *             Returns a Job that can be cancelled if the user navigates away.
 *             Parameter: (code: String)
 */
@Composable
fun CodeEntryScreen(
    username: String,
    backToSignIn: () -> Unit,
    verifyWithSomethingElse: (() -> Unit)?,
    next: (String) -> Job
) {
    LaunchedEffect(Unit) {
        Log.i(TAG, "CodeEntryScreen displayed - username: $username")
    }

    var code by remember { mutableStateOf("") }
    var showError by remember { mutableStateOf(false) }
    val focusManager = LocalFocusManager.current
    val jobState = rememberCancellableJob()

    AuthenticatorScreenScaffold(
        title = "Enter a code",
        username = username,
        backToSignIn = {
            jobState.cancel()
            backToSignIn()
        },
        verifyWithSomethingElse = {
            jobState.cancel()
            verifyWithSomethingElse?.invoke()
        },
    ) {
        Column(
            modifier = Modifier.fillMaxWidth(),
            horizontalAlignment = Alignment.Start,
        ) {
            Text(
                text = "Enter code",
                fontWeight = FontWeight.Bold,
            )
            OutlinedTextField(
                value = code,
                onValueChange = { code = it },
                modifier = Modifier.fillMaxWidth(),
                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
                isError = showError,
            )
            if (showError) {
                Text(BLANK_FIELD_ERROR, color = Color.Red)
            }
        }

        Spacer(modifier = Modifier.height(16.dp))

        Button(
            onClick = {
                code.validateNotBlank(
                    onError = { showError = true },
                    onSuccess = {
                        focusManager.clearFocus()
                        jobState.addJob(next(it))
                    }
                )
            },
            enabled = !jobState.isActive,
            modifier = Modifier.fillMaxWidth(),
        ) {
            Text(text = "Next")
        }
    }
}

@PreviewLightDark
@Composable
fun CodeEntryScreenPreview() {
    DirectAuthAppTheme {
        CodeEntryScreen(
            username = "user1@okta.com",
            backToSignIn = {},
            verifyWithSomethingElse = {},
            next = { Job().apply { complete() }}
        )
    }
}
