/*
 * Copyright 2022-Present Okta, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.okta.directauth.cli;

import com.okta.authfoundation.client.ClientAssertion;
import com.okta.authfoundation.client.ClientAssertionProvider;
import com.okta.authfoundation.client.jvm.OAuth2ClientBuilder;
import com.okta.directauth.jvm.DirectAuthenticationFlowBuilder;
import io.jsonwebtoken.Jwts;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.security.KeyFactory;
import java.security.NoSuchAlgorithmException;
import java.security.PrivateKey;
import java.security.spec.InvalidKeySpecException;
import java.security.spec.PKCS8EncodedKeySpec;
import java.time.Duration;
import java.util.Base64;
import java.util.Date;
import java.util.Properties;
import java.util.UUID;
import java.util.function.Consumer;

/**
 * Reads confidential-client credentials (a client secret or a private_key_jwt signing key) from
 * {@code local.properties} at runtime and applies them to an {@link OAuth2ClientBuilder} or a
 * {@link DirectAuthenticationFlowBuilder}, so this CLI can demonstrate Pushed Authorization
 * Requests (PAR), Direct Authentication, and other confidential-client features against a
 * confidential OAuth2 client.
 *
 * <p>The private_key_jwt path registers a {@link ClientAssertionProvider}, which the SDK invokes
 * fresh for every client-authenticated request — every token/PAR request for {@link
 * OAuth2ClientBuilder}, and every token/challenge/oob-authenticate/primary-authenticate request
 * (including each iteration of an OOB poll) for {@link DirectAuthenticationFlowBuilder}. This
 * matters for spec compliance — per <a
 * href="https://developer.okta.com/docs/api/openapi/okta-oauth/guides/client-auth">Okta's client
 * authentication guide</a>, a `jti` may only be used once and `aud` must be the exact endpoint URL
 * being called, neither of which a single statically-built assertion can satisfy across more than
 * one request.
 *
 * <p><b>SECURITY — local testing only.</b> This intentionally reads secrets from a plain-text file
 * at runtime, rather than the sample's usual approach of baking {@code local.properties} values
 * into generated build-time constants (see {@code AppConfig}, generated by the {@code
 * generateAppConfig} Gradle task). Never embed a client secret or private key in compiled code or a
 * shipped artifact — that includes the {@code AppConfig} pattern used for non-secret values in this
 * same sample. Confidential-client authentication (client secret or private_key_jwt) is only
 * appropriate for clients that can keep a secret, such as a backend service. It must never be used
 * from a mobile or other public/untrusted client, since any secret embedded in an app that ships to
 * end-user devices can be extracted from the binary.
 *
 * <p>For real deployments, load the secret from a proper secrets manager or KMS/HSM-backed signer
 * (e.g. AWS Secrets Manager, HashiCorp Vault, Google Secret Manager, or your cloud provider's KMS
 * for a private_key_jwt signer) — never from a checked-out properties file.
 *
 * <p>To try this out, add one of the following to the {@code local.properties} file at the repo
 * root (never commit it):
 *
 * <pre>{@code
 * clientSecret=your-client-secret
 * }</pre>
 *
 * or, for private_key_jwt (a PKCS#8 PEM, e.g. from {@code openssl genpkey -algorithm RSA -pkeyopt
 * rsa_keygen_bits:2048 | openssl pkcs8 -topk8 -nocrypt}), with newlines escaped as {@code \n}:
 *
 * <pre>{@code
 * clientAssertionPrivateKeyPem=-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBg...\n-----END PRIVATE KEY-----\n
 * }</pre>
 */
final class ClientAuthentication {
  private static final String TAG = "ClientAuthentication";
  private static final String CLIENT_SECRET_PROPERTY = "clientSecret";
  private static final String CLIENT_ASSERTION_PEM_PROPERTY = "clientAssertionPrivateKeyPem";
  private static final String JWT_BEARER_CLIENT_ASSERTION_TYPE =
      "urn:ietf:params:oauth:client-assertion-type:jwt-bearer";
  private static final Duration CLIENT_ASSERTION_LIFETIME = Duration.ofMinutes(5);
  private static final int MAX_PARENT_DIRECTORIES_TO_SEARCH = 8;

  private ClientAuthentication() {}

  /**
   * Applies a client secret or private_key_jwt client assertion provider to {@code builder}, if
   * either is present in {@code local.properties}. Does nothing if neither is configured, leaving
   * the client a public client (the default for this sample).
   *
   * @param builder the builder to configure
   * @param clientId the OAuth 2.0 client ID, used as the {@code iss}/{@code sub} claims of a
   *     private_key_jwt assertion
   */
  static void configure(OAuth2ClientBuilder builder, String clientId) {
    configure(builder, clientId, findLocalProperties());
  }

  /**
   * Overload taking an already-loaded {@link Properties}, so the credential-selection logic can be
   * unit-tested without touching the filesystem.
   */
  static void configure(OAuth2ClientBuilder builder, String clientId, Properties localProperties) {
    applyLocalClientCredentials(
        clientId, localProperties, builder::setClientSecret, builder::setClientAssertionProvider);
  }

  /**
   * Applies a client secret or private_key_jwt client assertion provider to {@code builder}, if
   * either is present in {@code local.properties}. Does nothing if neither is configured, leaving
   * the client a public client (the default for this sample).
   *
   * <p>The private_key_jwt provider registered here is invoked fresh for every client-authenticated
   * request the Direct Authentication flow makes — including each iteration of an OOB poll — not
   * just once, since a single statically-built assertion could not satisfy the `jti`/`aud`
   * requirements across more than one request.
   *
   * @param builder the builder to configure
   * @param clientId the OAuth 2.0 client ID, used as the {@code iss}/{@code sub} claims of a
   *     private_key_jwt assertion
   */
  static void configure(DirectAuthenticationFlowBuilder builder, String clientId) {
    configure(builder, clientId, findLocalProperties());
  }

  /**
   * Overload taking an already-loaded {@link Properties}, so the credential-selection logic can be
   * unit-tested without touching the filesystem.
   */
  static void configure(
      DirectAuthenticationFlowBuilder builder, String clientId, Properties localProperties) {
    applyLocalClientCredentials(
        clientId, localProperties, builder::setClientSecret, builder::setClientAssertionProvider);
  }

  /**
   * Shared credential-selection logic for both {@link OAuth2ClientBuilder} and {@link
   * DirectAuthenticationFlowBuilder}: reads {@code clientSecret}/{@code
   * clientAssertionPrivateKeyPem} from {@code localProperties} and applies whichever is present via
   * {@code setClientSecret}/{@code setClientAssertionProvider}.
   */
  private static void applyLocalClientCredentials(
      String clientId,
      Properties localProperties,
      Consumer<String> setClientSecret,
      Consumer<ClientAssertionProvider> setClientAssertionProvider) {
    String clientSecret = localProperties.getProperty(CLIENT_SECRET_PROPERTY, "").trim();
    String clientAssertionPem =
        localProperties.getProperty(CLIENT_ASSERTION_PEM_PROPERTY, "").trim();

    if (!clientAssertionPem.isEmpty()) {
      if (!clientSecret.isEmpty()) {
        CliLogger.info(
            TAG,
            "Both clientSecret and clientAssertionPrivateKeyPem are set in local.properties; "
                + "using the private_key_jwt assertion and ignoring clientSecret.");
      }
      PrivateKey privateKey = parsePkcs8PrivateKey(clientAssertionPem);
      setClientAssertionProvider.accept(
          audience ->
              new ClientAssertion(
                  JWT_BEARER_CLIENT_ASSERTION_TYPE,
                  buildClientAssertionJwt(clientId, audience, privateKey)));
      CliLogger.info(
          TAG,
          "Using a private_key_jwt client assertion provider from local.properties (testing"
              + " only; a fresh JWT is signed for every request).");
    } else if (!clientSecret.isEmpty()) {
      setClientSecret.accept(clientSecret);
      CliLogger.info(TAG, "Using a client_secret from local.properties (testing only).");
    } else {
      CliLogger.debug(
          TAG,
          "No clientSecret or clientAssertionPrivateKeyPem in local.properties; continuing as a"
              + " public client.");
    }
  }

  static String buildClientAssertionJwt(String clientId, String audience, PrivateKey privateKey) {
    Date now = new Date();
    Date expiration = new Date(now.getTime() + CLIENT_ASSERTION_LIFETIME.toMillis());
    return Jwts.builder()
        .issuer(clientId)
        .subject(clientId)
        .audience()
        .add(audience)
        .and()
        .id(UUID.randomUUID().toString())
        .issuedAt(now)
        .expiration(expiration)
        .signWith(privateKey)
        .compact();
  }

  /**
   * Parses a PKCS#8 PEM-encoded private key (RSA or EC). PKCS#1 keys (headers of the form {@code
   * -----BEGIN RSA PRIVATE KEY-----}) are not supported; convert with {@code openssl pkcs8 -topk8
   * -nocrypt -in key.pem -out key-pkcs8.pem} first.
   */
  static PrivateKey parsePkcs8PrivateKey(String pem) {
    String base64 = pem.replaceAll("-----(BEGIN|END)[^-]*-----", "").replaceAll("\\s", "");
    byte[] der = Base64.getDecoder().decode(base64);
    PKCS8EncodedKeySpec spec = new PKCS8EncodedKeySpec(der);
    for (String algorithm : new String[] {"RSA", "EC"}) {
      try {
        return KeyFactory.getInstance(algorithm).generatePrivate(spec);
      } catch (InvalidKeySpecException ignored) {
        // Not this key type; try the next one.
      } catch (NoSuchAlgorithmException e) {
        throw new IllegalStateException("Unsupported key algorithm: " + algorithm, e);
      }
    }
    throw new IllegalStateException(
        "clientAssertionPrivateKeyPem must be a PKCS#8 RSA or EC private key "
            + "(-----BEGIN PRIVATE KEY-----).");
  }

  /**
   * Searches {@code local.properties} starting at the current working directory and walking up
   * parent directories, since the CLI may be launched from the repo root (Gradle {@code run}) or
   * from an unpacked distribution directory.
   */
  private static Properties findLocalProperties() {
    File directory = new File(System.getProperty("user.dir")).getAbsoluteFile();
    for (int i = 0; directory != null && i < MAX_PARENT_DIRECTORIES_TO_SEARCH; i++) {
      File candidate = new File(directory, "local.properties");
      if (candidate.isFile()) {
        Properties properties = new Properties();
        try (InputStream in = new FileInputStream(candidate)) {
          properties.load(in);
          return properties;
        } catch (IOException e) {
          CliLogger.error(TAG, "Failed to read " + candidate, e);
          return new Properties();
        }
      }
      directory = directory.getParentFile();
    }
    return new Properties();
  }
}
