package com.okta.directauth.app.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme colors
val LightBrand = Color(0xFF00297A)
val LightPrimary = Color(0xFF1662DD)
val LightSecondary = Color(0xFF1662DD)
val LightSurface = Color(0xFFFFFFFF)
val LightSurfaceBrand = Color(0xFF3F59E4)
val LightSurfaceSuccess = Color(0xFF008055)
val LightSurfaceDanger = Color(0xFFDA372C)
val LightSurfaceTag = Color(0xFFBCD1F5)
val LightBorder = Color(0xFFE4E5E7)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightOnSurfaceHighEmphasis = Color(0xFF1D1D21)
val LightOnSurfaceMediumEmphasis = Color(0xFF6E6E78)
val LightOnSurfaceTag = Color(0xFF1D1D21)
val LightSuccess = Color(0xFF008055)
val LightDanger = Color(0xFFDA372C)
val LightWarning = Color(0xFFFFC61C)
val LightAccent1 = Color(0xFF6194E8)
val LightAccent2 = Color(0xFFDAE6FA)
val LightAccent3 = Color(0xFFDBDBDB)
val LightBackgroundBase = Color(0xFFFFFFFF)
val LightBackgroundInformation = Color(0xFFFAFAFA)
val LightTimer = Color(0xFF1A31A9)
val LightLink = Color(0xFF1662DD)

// Dark theme colors
val DarkBrand = Color(0xFFFFFFFF)
val DarkPrimary = Color(0xFF1662DD)
val DarkInputTextPrimary = Color(0xFF788EE2) // Special primary color for input text in dark theme
val DarkSecondary = Color(0xFFFFFFFF)
val DarkSurface = Color(0xFF1E1E1E)
val DarkSurfaceSuccess = Color(0xFF008055)
val DarkSurfaceDanger = Color(0xFFDA372C)
val DarkSurfaceTag = Color(0xFF9BAAD7)
val DarkBorder = Color(0xFF393939)
val DarkOnPrimary = Color(0xFFFFFFFF)
val DarkOnSurfaceHighEmphasis = Color(0xFFFFFFFF)
val DarkOnSurfaceMediumEmphasis = Color(0x99FFFFFF)
val DarkOnSurfaceTag = Color(0xFF1D1D21)
val DarkSuccess = Color(0xFF008055)
val DarkDanger = Color(0xFFF66260)
val DarkWarning = Color(0xFFFFDE7E)
val DarkAccent1 = Color(0xFF6194E8)
val DarkAccent2 = Color(0xFF424242)
val DarkAccent3 = Color(0xFF393939)
val DarkBackgroundBase = Color(0xFF1E1E1E)
val DarkBackgroundInformation = Color(0xFF1E1E1E)
val DarkTimer = Color(0xFFB6C9FF)
val DarkLink = Color(0xFFA7B5EC)
