name: Deploy docs with Dokka

on:
  push:
    tags:
      - '*'
  pull_request:

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 18

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build docs
        run: ./gradlew dokkaHtmlMultiModule

      - name: Publish To Maven Local
        run: ./gradlew publishToMavenLocal

      - name: Deploy to Github Pages
        if: startsWith(github.push.ref, 'refs/tags/')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
