name: main

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name : Validate Gradle Wrapper
        uses : gradle/actions/wrapper-validation@v4

      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Run Tests
        run: ./gradlew :okta-idx-kotlin:assembleDebug testDebugUnitTest assembleAndroidTest

      - name: Upload Test Failures
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-failures
          path: |
            **/build/reports/tests/
            **/out/failures/

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Configure JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Lint
        run: ./gradlew spotlessCheck apiCheck

      - name: Upload Lint Failures
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: lint-failures
          path: |
            **/build/reports/tests/
            **/out/failures/
