name: main

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 18

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Tests
        run: ./gradlew assembleDebug testDebugUnitTest assembleAndroidTest

      - name: Upload Test Failures
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-failures
          path: |
            **/build/reports/tests/
            **/out/failures/

  lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 18

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Lint
        run: ./gradlew spotlessCheck apiCheck

      - name: Upload Test Failures
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-failures
          path: |
            **/build/reports/tests/
            **/out/failures/
